package com.cds.common.metrics.sink;

/**
 * Sink consumes the records generated by the metrics source.
 */
public interface Sink {
  /**
   * Starts the reporter polling.
   */
  void start();

  /**
   * Stops the reporter.
   */
  void stop();

  /**
   * Reports the current values of all metrics.
   */
  void report();
}
